### ISSUE TITLE
[Issue]: Remove DependencyInfoBlock for F-Droid

### ISSUE THREAD

**Issue by linsui** [StellarSand/Password-Monitor#2]
### Description

We find that there is a `DependencyInfoBlock` in your APK.

It's a [Signing block](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).

While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

### Steps to reproduce the issue

1.

### Terms

- [X] This issue occurs on the [latest version](https://github.com/StellarSand/Password-Monitor/releases/latest).
- [X] This is not a duplicate of another issue.

**Comment by StellarSand** [comment]
Done. :heavy_check_mark: 
Do I have to make a new release or shall I update the apk in the current release?

**Comment by linsui** [comment]
I thought you just need to update the apk. :)

**Comment by StellarSand** [comment]
Done.

**Comment by linsui** [comment]
Thanks!

**Comment by IzzySoft** [comment]
> I thought you just need to update the apk. :)

@linsui please don't recommend that. One should never "replace" what was already distributed. And it would not be the first time that a replaced APK broke verification at IzzyOnDroid – where it was already processed and then no longer matches as it was replaced afterwards (you know verification at IzzyOnDroid runs on a separate track – and F-Droid will have the same issue with their verification servers should someone else get the idea of replacing an APK between F-Droid building it and then verifying it on the verification servers).

If a new APK is needed, make a new release. Can be a minor maintenance release. But don't replace what was already out-and-about, please. Thanks!
